In [55]:
import pandas

In [52]:
import numpy as np

In [53]:
import matplotlib.pyplot as pl

In [68]:
import pylab as plt

In [69]:
data = pandas.read_excel("https://nasdaqbaltic.com/statistics/en/shares?download=1")

In [70]:
data

,Ticker,Name,ISIN,Currency,MarketPlace,List/segment,Average Price,Open Price,High Price,Low Price,Last close Price,Last Price,Price Change(%),Best bid,Best ask,Trades,Volume,Turnover,Industry,Supersector
0,AIR,Airobot Technologies,EE3100092792,EUR,TLN,First North Baltic Share List,3.950041,3.950,3.960,3.95,3.960,3.960,NaN,3.950,3.960,8.0,241.0,951.96,Industrials,Construction and Materials
1,AMG1L,Amber Grid,LT0000128696,EUR,VLN,Baltic Secondary List,1.240000,1.240,1.240,1.24,1.240,1.240,NaN,1.230,1.240,7.0,102.0,126.48,Energy,Energy
2,APG1L,Apranga,LT0000102337,EUR,VLN,Baltic Main List,2.709137,2.710,2.720,2.70,2.710,2.705,-0.18,2.700,2.710,128.0,14677.0,39762.00,Consumer Discretionary,Retail
3,ARC1T,Arco Vara,EE3100034653,EUR,TLN,Baltic Main List,1.776497,1.770,1.795,1.77,1.770,1.770,NaN,1.765,1.780,66.0,1530.0,2718.04,Real Estate,Real Estate
4,AUG1L,AUGA group,LT0000127466,EUR,VLN,Baltic Main List,0.441299,0.442,0.445,0.44,0.442,0.440,-0.45,0.440,0.442,47.0,7042.0,3107.63,Consumer Staples,"Food, Beverage and Tobacco"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,VBL1L,Vilniaus baldai,LT0000104267,EUR,VLN,Baltic Secondary List,7.000000,7.000,7.000,7.00,6.800,7.000,2.94,6.900,7.000,7.0,7.0,49.00,Consumer Discretionary,Consumer Products and Services
71,VEF1R,VEF,LV0000101079,EUR,RIG,Baltic Secondary List,NaN,5.600,NaN,NaN,5.600,5.600,NaN,5.150,5.600,NaN,NaN,NaN,Real Estate,Real Estate
72,VIRSI,VIRŠI-A,LV0000101848,EUR,RIG,First North Baltic Share List,4.482110,4.460,4.500,4.46,4.460,4.500,0.90,4.480,4.490,52.0,2521.0,11299.40,Consumer Discretionary,Retail
73,VLP1L,Vilkyškių pieninė,LT0000127508,EUR,VLN,Baltic Main List,5.154370,5.240,5.240,5.12,5.200,5.120,-1.54,5.100,5.120,17.0,2071.0,10674.70,Consumer Staples,"Food, Beverage and Tobacco"
74,ZMP1L,Žemaitijos pienas,LT0000121865,EUR,VLN,Baltic Secondary List,NaN,1.820,NaN,NaN,1.820,1.820,NaN,1.790,1.820,NaN,NaN,NaN,Consumer Staples,"Food, Beverage and Tobacco"